LPS-120240 portal-search-elasticsearch7-impl: test: Add new dependencies bc-fips and bcpg-fips required by the ES PluginCli
Otherwise we get

Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/jcajce/provider/BouncyCastleFipsProvider
	at org.elasticsearch.plugins.PluginCli.<init>(PluginCli.java:41)

when running in Embedded mode.

See https://github.com/elastic/elasticsearch/blob/v7.9.0/distribution/tools/plugin-cli/build.gradle#L27-L28

https://issues.liferay.com/browse/LPS-120240

Signed-off-by: Tibor Lipusz <tibor.lipusz@liferay.com>