COMMERCE-530 fix jspc
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.liferay.jasper.jspc.JspC.main(JspC.java:52)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.jasper.jspc.JspC._runWithClassPath(JspC.java:168)
        at com.liferay.jasper.jspc.JspC.main(JspC.java:46)
Caused by: java.lang.NoClassDefFoundError: com/liferay/frontend/taglib/util/TagAccessor
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetPublicMethods(Class.java:2902)
        at java.lang.Class.getMethods(Class.java:1615)
        at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1336)
        at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1197)
        at java.beans.Introspector.getBeanInfo(Introspector.java:426)
        at java.beans.Introspector.getBeanInfo(Introspector.java:173)
        at java.beans.Introspector.getBeanInfo(Introspector.java:260)
        at java.beans.Introspector.<init>(Introspector.java:407)
        at java.beans.Introspector.getBeanInfo(Introspector.java:173)
        at org.apache.jasper.runtime.JspRuntimeLibrary.getWriteMethod(JspRuntimeLibrary.java:779)
        at org.apache.jasper.compiler.Validator$ValidateVisitor.checkSetter(Validator.java:1056)
        at org.apache.jasper.compiler.Validator$ValidateVisitor.checkXmlAttributes(Validator.java:1137)
        at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:859)
        at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1502)