COMMERCE-4016 Avoid generics to dodge SearchUtil$SearchContext
SearchUtil$SearchContext was just introduced into 7.1.x on May 21, 2020
and therefore isn't present in any released fixpacks. With the code
as it was before, the lambda we had would accept whatever class
SearchUtil.search expected, as long as it conformed to the API we
were using (i.e. portal kernel SearchContext). At compile-time,
since we use a project dependency, the compiler would use the
SearchUtil$SearchContext class, which would get baked into the
artifact -- but at runtime, for any released version, that class
would not be present, yielding NoClassDefFoundErrors.

This workaround avoids generics so that the compiler doesn't bake
SearchUtil$SearchContext into the artifact. Since that problematic
class extends portal kernel SearchContext, we can use the portal
kernel class at runtime without any problem, avoiding the issue.